version: '3.7'

services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn mpd.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=development
      - SECRET_KEY=^-a9g900u%as99&lh^sk_-ejv)&cde%38_9h70f1@8d5%s4ao6
      - DEBUG=1
    volumes: 
       - .:/code/mpdatabase
    ports: 
      - 8000:8000
    depends_on: 
      - db
    links: 
      - db:db
  db:
    image: postgres:11
    volumes:  
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres_data:

