# Generated by Django 2.2.7 on 2021-01-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersons', '0002_auto_20210107_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
