# Generated by Django 2.2.7 on 2021-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersons', '0003_auto_20210107_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
